version: "3"

services:
  traefik:
    image: traefik:v2.4
    container_name: vue-to-do-app-traefik-dev
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false 
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    container_name: vue-to-do-app-frontend-dev
    build: 
      context: ./frontend
      target: dev
    volumes:
      - ./frontend/src:/app/src
    labels: 
      traefik.enable: true
      traefik.http.routers.frontend.rule: Host(`localhost`)
      traefik.http.routers.frontend.entrypoints: web
      traefik.http.services.frontend.loadbalancer.server.port: 8080